name: CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

  workflow_dispatch:
  
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
      - name: Install Dependencies
        run: |
          python -m pip install -e .[test]
      - name: Build coverage file
        run: |
          pytest -v --cov=crawler
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
